// Generated by gencpp from file depthcam/speed.msg
// DO NOT EDIT!


#ifndef DEPTHCAM_MESSAGE_SPEED_H
#define DEPTHCAM_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace depthcam
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : X_speed(0.0)
    , Y_speed(0.0)
    , Z_speed(0.0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : X_speed(0.0)
    , Y_speed(0.0)
    , Z_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _X_speed_type;
  _X_speed_type X_speed;

   typedef float _Y_speed_type;
  _Y_speed_type Y_speed;

   typedef float _Z_speed_type;
  _Z_speed_type Z_speed;





  typedef boost::shared_ptr< ::depthcam::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthcam::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::depthcam::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::depthcam::speed > speedPtr;
typedef boost::shared_ptr< ::depthcam::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthcam::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthcam::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthcam::speed_<ContainerAllocator1> & lhs, const ::depthcam::speed_<ContainerAllocator2> & rhs)
{
  return lhs.X_speed == rhs.X_speed &&
    lhs.Y_speed == rhs.Y_speed &&
    lhs.Z_speed == rhs.Z_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthcam::speed_<ContainerAllocator1> & lhs, const ::depthcam::speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthcam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthcam::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthcam::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthcam::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthcam::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthcam::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthcam::speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthcam::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b206176458d8484913bad2dea5ffce8";
  }

  static const char* value(const ::depthcam::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b206176458d8484ULL;
  static const uint64_t static_value2 = 0x913bad2dea5ffce8ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthcam::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthcam/speed";
  }

  static const char* value(const ::depthcam::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthcam::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 X_speed\n"
"float32 Y_speed\n"
"float32 Z_speed\n"
"\n"
;
  }

  static const char* value(const ::depthcam::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthcam::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X_speed);
      stream.next(m.Y_speed);
      stream.next(m.Z_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthcam::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthcam::speed_<ContainerAllocator>& v)
  {
    s << indent << "X_speed: ";
    Printer<float>::stream(s, indent + "  ", v.X_speed);
    s << indent << "Y_speed: ";
    Printer<float>::stream(s, indent + "  ", v.Y_speed);
    s << indent << "Z_speed: ";
    Printer<float>::stream(s, indent + "  ", v.Z_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHCAM_MESSAGE_SPEED_H
